In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(("email.csv"))

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [6]:
df.duplicated().sum()

np.int64(415)

In [7]:
print("=== LABEL CATEGORY Percentage ===")
label_counts = df['Category'].value_counts()
label_percentages = df['Category'].value_counts(normalize=True) * 100

label_summary = pd.DataFrame({
    'Count': label_counts,
    'Percentage': label_percentages
})
print(label_summary)

=== LABEL CATEGORY Percentage ===
                Count  Percentage
Category
ham              4825   86.578145
spam              747   13.403912
{"mode":"full"      1    0.017944

In [8]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Category"] = le.fit_transform(df["Category"])

In [10]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [11]:
df = df.drop_duplicates()

In [12]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [13]:
import torch
import re
import nltk

In [14]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [15]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/shivendrasahu/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [16]:
def clean_text(text):
    #Convert to lower case
    text = text.lower()

    #remove special character
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    #remove extra whitespace
    text = re.sub(r's+', ' ', text).strip()

    #Tokenize and remove stop words
    words = text.split()
    words = [word for word in words if word not in stopwords]

    #Appply stemming
    words = [stemmer.stem(word) for word in words]
    return " ".join(words)

In [17]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [ ]:
# Apply cleaning
# ensure clean_text uses the stop_words set (not the corpus reader)
stopwords = stop_words
df['cleaned_message'] = df['Message'].apply(clean_text)

TypeError: argument of type 'WordListCorpusReader' is not iterable

In [ ]:
df.columns

Index(['Category', 'Message', 'cleaned_message'], dtype='object')