In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pd.read_csv(("email.csv"))

In [16]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [17]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [18]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [19]:
df.duplicated().sum()

np.int64(415)

In [20]:
print("=== LABEL CATEGORY Percentage ===")
label_counts = df['Category'].value_counts()
label_percentages = df['Category'].value_counts(normalize=True) * 100

label_summary = pd.DataFrame({
    'Count': label_counts,
    'Percentage': label_percentages
})
print(label_summary)

=== LABEL CATEGORY Percentage ===
                Count  Percentage
Category
ham              4825   86.578145
spam              747   13.403912
{"mode":"full"      1    0.017944

In [21]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Category"] = le.fit_transform(df["Category"])

In [23]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [25]:
df = df.drop_duplicates()

In [26]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
import torch
import re
import nltk
imporrt nltk

SyntaxError: invalid syntax (837843877.py, line 3)

In [32]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [ ]:
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

In [ ]:
def clean_text(text):
    #Convert to lower case
    text = text.lower()

    #remove special character
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    #remove extra whitespace
    text = re.sub(r's+', ' ', text).strip()

    #Tokenize and remove stop words
    words = text.split()
    words = [word for word in words if word not in stopwords]

    #Appply stemming